export const CONFIG = {
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN || '8955584134:AAGLQkihVhpKGxTu4CTBcaFplZ5mwCzbtbk',
  SCAN_INTERVAL_SECONDS: 60,
  COOLDOWN_MINUTES: 30,
  DEFAULT_ACCOUNT_BALANCE: 1000, // Default $1000, user can change with /kasa
  DEFAULT_RISK_PERCENT: 1,       // Risk max 1% of account per trade
  DEFAULT_WATCHLIST: [
    'BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT', 'XRPUSDT', 
    'DOGEUSDT', 'SUIUSDT', 'PEPEUSDT', 'NEARUSDT', 'AVAXUSDT', 
    'LINKUSDT', 'ADAUSDT', 'APTUSDT', 'RENDERUSDT', 'FTMUSDT', 
    'WIFUSDT', 'SHIBUSDT', 'LTCUSDT', 'DOTUSDT', 'TAOUSDT'
  ],
  RSI_PERIOD: 14,
  RSI_OVERSOLD: 30,
  RSI_OVERBOUGHT: 70,
  VOLUME_MULTIPLIER: 3.0
};
